#!/bin/bash
# Restore Script for Cryptography Lab

# Restore Script restores the backup of the database used by the lab.
# Since there is no database being used for Cryptography Lab, 
# the script does nothing. 

echo "There is no database used for the lab."
